// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caxgtmsactzelceufbpv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNheGd0bXNhY3R6ZWxjZXVmYnB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTk5NzAsImV4cCI6MjA3MDIzNTk3MH0.F10Ka-bX9irEZXLtJd_ndt7-7RfWDT2heUrdWF_libw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});